import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';
import { days, sites, bookings } from '../trip.mjs';
const restaurantData = JSON.parse(await readFile(new URL('../restaurants.json', import.meta.url), 'utf8'));
const groups = restaurantData.groups;
const esc = s => String(s ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const map = q => `https://yandex.ru/maps/?text=${encodeURIComponent(q)}`;
const route = places => `https://yandex.ru/maps/?rtext=${encodeURIComponent(places.join('~'))}&rtt=auto`;
const pin = '<svg class="map-pin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="10" r="2.5" stroke="currentColor" stroke-width="2"/></svg>';
const link = (url,label,cls='') => `<a class="button ${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${cls==='map'?pin:''}${esc(label)}${cls==='map'?'':' ↗'}</a>`;
function restaurants(key){
  const list = key === 'minskFinal' ? (groups.minskFinal || [...groups.minsk].reverse()) : groups[key];
  if (!list || list.length < 3) throw Error(`Need 3 restaurants for ${key}`);
  return `<details class="meal-list"><summary>${list.length} варианта · где поесть</summary>${list.map(r=>`<div class="restaurant"><div class="restaurant-head"><h4>${esc(r.name)}</h4><span class="restaurant-price">${esc(r.price)}</span></div><p>${esc(r.description)}</p>${r.note?`<p class="note">${esc(r.note)}</p>`:''}<div class="actions">${link(map(r.mapQuery),'Яндекс Карты','map')}${r.website?link(r.website,'Официальный сайт'):r.source?link(r.source,'Карточка места'):''}</div></div>`).join('')}</details>`;
}
const types = {road:'🚗 Дорога',hotel:'🏨 Отель',sight:'🏰 Впечатления',food:'🍽 Еда',booking:'🎟 Экскурсия',metro:'Ⓜ Метро',shopping:'🛍 Покупки'};
function event(e){return `<article class="event ${esc(e.type)} ${e.optional?'optional':''}"><div class="event-top"><time>${esc(e.time)}</time><span class="type">${esc(types[e.type])}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="actions">${e.route?link(route(e.route),'Яндекс Карты','map'):e.map?link(map(e.map),'Яндекс Карты','map'):''}${e.site?link(sites[e.site],'Официальный сайт'):''}${e.booking?`<a class="button" href="#booking-${e.booking}">🎟 Билеты / экскурсия</a>`:''}</div>${e.note?`<p class="note">${esc(e.note)}</p>`:''}${e.meal?restaurants(e.meal):''}</article>`;}
function day(d){return `<section class="day-section" id="day-${d.id}" data-title="${esc(d.subtitle)}" data-summary="${esc(d.summary)}" aria-labelledby="title-${d.id}"><header class="day-header"><div class="date-stamp">${d.id}<span>октября</span></div><div class="day-title"><p class="eyebrow">${esc(d.weekday)} <span class="today-badge" data-today="${d.id}" hidden>Сегодня</span></p><h2 id="title-${d.id}">${esc(d.title)}</h2><p>${esc(d.subtitle)}</p><a class="route-link" href="${esc(route(d.route))}" target="_blank" rel="noopener noreferrer">${pin} Маршрут дня в Яндекс Картах ↗</a></div></header>${d.note?`<p class="note day-note">${esc(d.note)}</p>`:''}<div class="timeline">${d.events.map(event).join('')}</div></section>`;}
const routeArt = `<svg class="route-art" viewBox="0 0 420 275" role="img" aria-label="Схема маршрута: Москва, Гродно, Мир, Несвиж, Сула, Минск, Жодино, Москва"><defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#dbe2d8"/></pattern></defs><rect x="2" y="2" width="416" height="270" rx="20" fill="url(#dots)"/><path d="M53 47C8 79 22 167 71 178S161 246 181 203 159 137 209 143 264 214 302 169 380 179 369 103 309 80 332 41" fill="none" stroke="#aec0a5" stroke-width="3" stroke-linecap="round" stroke-dasharray="5 6"/><g fill="#1c5140" stroke="#f5f4ee" stroke-width="4"><circle cx="53" cy="47" r="7"/><circle cx="71" cy="178" r="7"/><circle cx="181" cy="203" r="7"/><circle cx="209" cy="143" r="7"/><circle cx="302" cy="169" r="7"/><circle cx="369" cy="103" r="7"/><circle cx="332" cy="41" r="7"/></g><text x="70" y="43" class="route-label">Москва</text><text x="70" y="58" class="route-small">04.10 · старт 09:30</text><text x="35" y="201" class="route-label">Гродно</text><text x="34" y="215" class="route-small">04–06 октября</text><text x="162" y="229" class="route-label">Мир</text><text x="192" y="121" class="route-label">Несвиж</text><text x="284" y="194" class="route-label">Сула</text><text x="313" y="108" class="route-label">Минск</text><text x="313" y="124" class="route-small">07–09 октября</text><text x="261" y="25" class="route-label">Жодино</text><text x="348" y="44" class="route-small">→ домой</text><g stroke="#7d9373" stroke-width="1.8" fill="#e3ebde"><path d="m117 108 11-22 11 22h-7v9h-8v-9Z"/><path d="m91 118 8-17 8 17h-5v7h-6v-7Z"/><path d="m252 71 9-20 9 20h-6v8h-6v-8Z"/><path d="M121 163v-24h8v-7h7v7h8v-7h7v7h8v24Zm13 0v-11h12v11"/></g></svg>`;
const hotels = [{dates:'04–06 октября',name:'Kronon Park Hotel',city:'Гродно',site:'kronon'},{dates:'06–07 октября',name:'Hotel Palace / «Палац»',city:'Несвиж',site:'palace'},{dates:'07–09 октября',name:'Beijing Hotel',city:'Минск',site:'beijing'}];
const html = `<!doctype html>
<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#1c5140"><meta name="description" content="Семейная поездка по Беларуси 4–9 октября 2026: маршрут по дням, отели, замки, рестораны, БЕЛАЗ и Яндекс Карты."><meta property="og:title" content="Беларусь · наше маленькое путешествие"><meta property="og:description" content="4–9 октября 2026. Шесть дней, пятеро путешественников и один большой маршрут."><meta property="og:type" content="website"><title>Беларусь · семейная поездка 4–9 октября 2026</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script type="module" src="/app.mjs"></script></head><body>
<a href="#days" class="skip">К маршруту</a><header class="wrap"><div class="topline"><div class="brand"><span class="brand-mark" aria-hidden="true">↟</span>Наше путешествие</div><a class="toplink" href="#bookings">🎟 Что забронировать ↗</a></div><div class="hero"><div><p class="eyebrow">Осень 2026 · семейный road trip</p><h1>Беларусь.<br><em>Вместе и не спеша.</em></h1><p class="hero-copy">Лесные утра, старые замки, большие машины.<br>И шесть дней только для нас.</p><div class="meta"><span class="pill">4 — 9 октября</span><span class="pill">2 взрослых + 3 детей</span><span class="pill">12, 10 и 7 лет</span></div></div><div>${routeArt}<p class="route-caption">Схема путешествия · навигация — в Яндекс Картах</p></div></div><section class="today" aria-label="Сегодня в поездке"><div id="today-content"><p class="eyebrow">Сегодня · наш маршрут</p><h2>Все планы под рукой</h2><p>Выберите дату ниже. Автоматический день определяется по времени Минска и Москвы — UTC+3.</p><a class="button today-button" href="#day-04">К началу путешествия ↗</a></div><span class="today-icon" aria-hidden="true">↗</span></section></header>
<nav class="day-nav" aria-label="Дни поездки"><div class="nav-inner"><span class="nav-label">Октябрь / 2026</span>${days.map(d=>`<a data-day="${d.id}" href="#day-${d.id}" aria-label="${d.id} октября: ${esc(d.subtitle)}">${d.id}<small>${({'04':'ВС','05':'ПН','06':'ВТ','07':'СР','08':'ЧТ','09':'ПТ'})[d.id]}</small></a>`).join('')}</div></nav>
<main class="wrap" id="days"><div class="main-grid"><div>${days.map(day).join('')}</div><aside class="sidebar" aria-label="Полезное в поездке"><section class="side-block"><h2>Три отеля. Всё решено.</h2><p>Бронирования уже есть, отели сохраняем.</p><div class="hotel-grid">${hotels.map(h=>`<article class="hotel-card"><p class="eyebrow">${h.dates}</p><h3>${h.name}</h3><div class="hotel-status">✓ Забронирован · ${h.city}</div><div class="actions">${link(map(`${h.name} ${h.city}`),'Яндекс Карты','map')}${link(sites[h.site] || sites.nesvizh,'Официальный сайт')}</div></article>`).join('')}</div></section><section class="side-block"><h2>Сначала — БЕЛАЗ</h2><p>09 октября · 2 взрослых + дети 12, 10 и 7 лет. Нужно подтвердить слот и доступные детям активности.</p><a class="button" href="#booking-belaz">🎟 К деталям бронирования</a></section><section class="side-block"><h2>Наш ритм</h2><p>Завтраки около 09:00, паузы по дороге, время в бассейне и никаких обязательных дополнительных музеев.</p><p>Все часы — местные: Москва и Беларусь, UTC+3. Время переездов ориентировочное.</p><div class="legend"><span>🚗 Дорога</span><span>🏨 Отель</span><span>🏰 Место</span><span>🍽 Еда</span><span>🎟 Бронь</span></div><p>₽ · просто &nbsp; ₽₽ · средний уровень &nbsp; ₽₽₽ · выше среднего. Это относительный уровень, не цена в рублях.</p></section></aside></div>
<section class="bookings" id="bookings"><div class="section-heading"><h2>Забронировать / проверить</h2><span>Приоритет сверху вниз</span></div><p class="source-note">Цвет обозначает приоритет. Экскурсии ещё не забронированы; наличие мест подтверждает организатор.</p><div class="booking-list">${bookings.map(b=>`<article class="booking-card ${b.priority}" id="booking-${b.id}"><p class="eyebrow">${b.symbol} ${esc(b.date)}</p><h3>${esc(b.title)}</h3><span class="status">${esc(b.status)}</span><p>${esc(b.text)}</p><div class="actions">${link(sites[b.site],'Официальный сайт')}${b.order?link(b.order,'Билеты / экскурсия'):''}${b.phone?`<a class="button map" href="tel:${esc(b.phone)}">Позвонить ${esc(b.phoneDisplay||b.phone)}</a>`:''}</div></article>`).join('')}</div></section>
<section class="practical"><h2>Чтобы просто отдыхать</h2><ul><li>Яндекс Карты — основной навигатор. Скачайте карты Беларуси и дороги заранее; ссылки на места используют поиск по названию — проверьте нужный адрес.</li><li>У отелей уточните детские часы бассейна, доступ в SPA и поздний ужин. Забронированный номер сам по себе не подтверждает все SPA-услуги.</li><li>Ресторанные варианты проверены по доступным источникам 04.10.2026. Наличие столов и часы кухни на нужный вечер требуют уточнения.</li><li>На 04 октября достопримечательностей нет. На 08 октября БГУ остаётся необязательным. Темп можно менять по настроению детей.</li><li>После БЕЛАЗа 09 октября предстоит длинная дорога: фактическое прибытие домой может быть ночью 10 октября.</li></ul></section>
<details class="source-note"><summary>Источники и актуальность ↗</summary><p>Проверка доступных веб-источников: 4 октября 2026. Программы и часы могут меняться. Подтверждённых экскурсионных броней нет.</p><ul>${Object.entries(sites).map(([key,url])=>`<li><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(new URL(url).hostname)}</a></li>`).join('')}<li><a href="https://www.zara.com/by/ru/stores-locator/zara-minsk-dana-mall-s12168" target="_blank" rel="noopener noreferrer">Zara · официальный локатор Dana Mall</a></li><li><a href="https://shop.mango.com/by/ru/stores/" target="_blank" rel="noopener noreferrer">Mango · официальный локатор</a></li></ul></details>
</main><footer class="wrap"><div class="footer"><span>Беларусь, октябрь 2026 · наше семейное путешествие</span><span>Планы гибкие. Воспоминания — навсегда.</span></div></footer></body></html>`;
await mkdir(new URL('../dist/',import.meta.url), {recursive:true});
await cp(new URL('../public/',import.meta.url),new URL('../dist/',import.meta.url),{recursive:true});
await writeFile(new URL('../dist/index.html',import.meta.url),html);
console.log(`Built ${days.length} days, ${bookings.length} booking cards, ${Buffer.byteLength(html)} bytes of HTML`);
